# Generated by Django 4.0.4 on 2022-04-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='charity',
            name='description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charity',
            name='website',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charity',
            name='logo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='charity',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='charity',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='charity', to='charities.category'),
        ),
    ]
