# Generated by Django 4.0.4 on 2022-04-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_category_charity_description_charity_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
