# Generated by Django 4.0.4 on 2022-04-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0003_alter_charity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
