# Generated by Django 4.0.4 on 2022-04-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('frequency', models.CharField(choices=[('O', 'Once'), ('M', 'Monthly')], default='O', max_length=10)),
            ],
        ),
    ]
